### ISSUE TITLE
Скрывать значки напротив ников пользователей

### ISSUE THREAD

**Issue by agentgoblin** [korney4eg/gg_staff#7]
Опционально, поэтому скрыть по-умолчанию под комментарием
```css
/* Скрыть иконки перед именами пользователей */
.chat-container .user .icon { display: none; }

```
